// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxbMG9kPVeHWiOE7tpCpjqIKej9akGh98',
    appId: '1:865924766479:web:77d96866fd9439b828bc7a',
    messagingSenderId: '865924766479',
    projectId: 'smart-grocery-3b932',
    authDomain: 'smart-grocery-3b932.firebaseapp.com',
    storageBucket: 'smart-grocery-3b932.firebasestorage.app',
    measurementId: 'G-EFQ6JBWXSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACUbBfOv-zW21lsH6KgZqda4o_Rq2aLqI',
    appId: '1:865924766479:android:737b3ebe632d2c1228bc7a',
    messagingSenderId: '865924766479',
    projectId: 'smart-grocery-3b932',
    storageBucket: 'smart-grocery-3b932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuWzLyKhV5-DUOq0tOmUDhPEn1l_w0_8g',
    appId: '1:865924766479:ios:c30c570598f19dd428bc7a',
    messagingSenderId: '865924766479',
    projectId: 'smart-grocery-3b932',
    storageBucket: 'smart-grocery-3b932.firebasestorage.app',
    iosClientId: '865924766479-3pm7tt91ha5noa5410scl0a0gbev9n03.apps.googleusercontent.com',
    iosBundleId: 'com.example.governmentSmartGroceryApp',
  );
}
