class EnglishStrings {
  static const Map<String, String> strings = {
    'settings': 'Settings',
    'preferences': 'PREFERENCES',
    'language': 'Language',
    'notifications': 'Notifications',
    'mark_all': 'Mark All',
    'clear_all': 'Clear All',
    'select_language': 'Select Language',
    'no_notifications': 'No notifications yet — favourite products to get price alerts.',
    'clear_notifications_title': 'Clear All Notifications',
    'clear_notifications_message': 'This will remove every notification. This cannot be undone.',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'app_name': 'Smart Grocery',
    'coming_soon': 'Coming soon',
    'search_products': 'Search products...',
    'quick_actions': 'Quick Actions',
    'search': 'Search',
    'nearby': 'Nearby',
    'cart': 'Cart',
    'trends': 'Trends',
    'price_alerts': 'Price Alerts',
    'view_all': 'View All',
    'no_price_alerts': 'No price alerts yet.',
    'recent_products': 'Recent Products',
    'no_recent_products': 'No recent products yet.',
    'guest': 'Guest',
    'registered_user': 'Registered User',
    'dashboard': 'Dashboard',
    'search_products_menu': 'Search Products',
    'nearby_supermarkets': 'Nearby Supermarkets',
    'price_trends': 'Price Trends',
    'my_budget': 'My Budget',
    'favourites': 'Favourites',
    'profile': 'Profile',
    'about': 'About',
    'logout': 'Logout',
    'clear_recent_searches_title': 'Clear Recent Searches',
    'clear_recent_searches_message': 'This will remove all of your recent searches.',
    'search_error': 'Something went wrong while searching.',
    'removed_from_favourites': 'Removed from favourites',
    'added_to_favourites': 'Added to favourites',
    'added_to_cart': 'Added to cart',
    'please_try_again': 'Please try again',
    'view': 'View',
    'search_products_hint': 'Search products (e.g. ayam, beras, oil)...',
    'filter': 'Filter',
    'results': 'Results',
    'no_products_found': 'No products found — try another search.',
    'clear_filters': 'Clear Filters',
    'or_browse_category': 'Or browse a category',
    'search_prompt': 'Search for a product to compare prices across supermarkets.',
    'product_details': 'Product Details',
    'product_not_found': 'This product could not be found.',
    'could_not_load_product': 'Could not load this product.',
    'add_to_cart': 'Add to Cart',
    'could_not_load_pricing': 'Could not load pricing for this product.',
    'no_price_data': 'No price data available for this product yet.',
    'price_varies_by_store': 'Price may vary by store',
    'cheapest_at': 'Cheapest at',
    'avg_price': 'Avg. Price',
    'price_trend': 'Price Trend',
    'trend_rising': 'Rising',
    'trend_falling': 'Falling',
    'trend_stable': 'Stable',
    'price_comparison': 'Price Comparison',
    'view_all_stores': 'View All Stores',
    'product_information': 'Product Information',
    'category': 'Category',
    'item_group': 'Item Group',
    'unit': 'Unit',
    'compare_prices': 'Compare Prices',
    'could_not_load_prices': 'Could not load prices for this product.',
    'could_not_load_supermarkets': 'Could not load supermarket details.',
    'sort': 'Sort:',
    'sort_price': 'Price',
    'sort_distance': 'Distance',
    'sort_alphabetical': 'Alphabetical',
    'tap_store_to_add': 'Tap a store to add',
    'lowest': 'Lowest',
    'average': 'Average',
    'highest': 'Highest',
    'cheapest': 'Cheapest',
    'locating': 'Locating…',
    'all_categories': 'All Categories',
    'price_range': 'Price Range',
    'sort_by': 'Sort By',
    'reset': 'Reset',
    'apply': 'Apply',
    'recent_searches': 'Recent Searches',
    'no_price_history_available': 'No price history available.',
    'date': 'Date',
    'store': 'Store',
    'price': 'Price',
    'supermarket': 'Supermarket',
    'search_results': 'Search Results',
    'could_not_load_products': 'Could not load products.',
    'search_product_hint': 'Search product...',
    'search_trend_instruction': 'Type in the search bar to find product price trends.',
    'no_notifications_yet': 'No notifications yet — favourite products to get price alerts.',
    'clear_all_notifications_title': 'Clear All Notifications',
    'clear_all_notifications_message': 'This will remove every notification. This cannot be undone.',
    'could_not_load_notifications': 'Could not load notifications.',
    'just_now': 'Just now',
    'min_ago': 'min ago',
    'hours_ago': 'h ago',
    'days_ago': 'd ago',
    'price_unavailable': 'Price unavailable',
    'view_details': 'View Details',
    'remove': 'Remove',
    'clear_all_favourites_title': 'Clear All Favourites',
    'clear_all_favourites_message': 'This will remove every favourited product. This cannot be undone.',
    'log_in_to_save_favourites': 'Log in to save favourites',
    'log_in_to_save_favourites_desc': 'Favourite products you love and get notified when their price changes.',
    'login': 'Login',
    'your_favourites': 'Your Favourites',
    'your_favourites_desc': 'Quick access to products you save for later.',
    'search_favourites_hint': 'Search favourites...',
    'all_favourites': 'All Favourites',
    'done': 'Done',
    'edit': 'Edit',
    'no_favourites_added': "You haven't added any favourites yet.",
    'no_favourites_matched': 'No favourites match your search.',
    'could_not_load_favourites': 'Could not load your favourites.',
    'filter_supermarkets': 'Filter Supermarkets',
    'open_now': 'Open Now',
    'minimum_rating': 'Minimum Rating',
    'and_above': '& Above',
    'maximum_distance': 'Maximum Distance',
    'location_required': 'Location Required',
    'location_service_disabled_msg': "Please turn on your device's location service to discover nearby supermarkets.",
    'location_permission_denied_msg': 'Please allow location permission to discover nearby supermarkets.',
    'turn_on_location': 'Turn On Location',
    'grant_permission': 'Grant Permission',
    'retry': 'Retry',
    'all': 'All',
    'grocery': 'Grocery',
    'hypermarket': 'Hypermarket',
    'convenience': 'Convenience',
    'search_supermarket_hint': 'Search supermarket...',
    'open': 'Open',
    'closed': 'Closed',
    'navigate': 'Navigate',
    'view_prices': 'View Prices',
    'nearby_stores': 'Nearby Stores',
    'found': 'found',
    'no_supermarkets_found': 'No supermarkets found.',
    'address': 'Address',
    'product_catalogue': 'Product Catalogue',
    'no_product_data_title': 'No product data yet',
    'no_product_data_desc': 'Products available in this supermarket will appear here.',
    'check_connection_retry': 'Please check your connection and try again.',
    'no_comparison_data_title': 'No comparison data yet',
    'no_comparison_data_desc': 'Compare product prices with other supermarkets.',
    'could_not_load_comparison': 'Could not load comparison',
    'no_products_found_desc': "We don't have price data for this store's products yet.",
    'approximate_match_warning': 'Showing the closest matching store in our price database — it may not be an exact match.',
    'showing_products_count': 'Showing {shown} of {total} products available at this store.',
    'best_prices_found_title': 'Best prices found here',
    'best_prices_found_desc': "This store already has the lowest price we've found for its products.",
    'price_here_vs_elsewhere': 'RM{here} here · RM{elsewhere} elsewhere',
    'price_each': 'RM{price} each',
    'choose_a_store': 'Choose a Store',
    'could_not_load_store_options': 'Could not load store options for this product.',
    'no_store_price_available': 'No store currently has a price for this product.',
    'clear_cart': 'Clear Cart',
    'clear_cart_message': 'This will remove every item from your cart.',
    'removed_item': 'Removed {name}',
    'undo': 'Undo',
    'empty_cart_message': 'Your cart is empty.\nAdd products while browsing or comparing prices.',
    'could_not_load_cart': 'Could not load your cart.',
    'cheapest_single_store': 'Cheapest Single Store',
    'single_store_comparison_subtitle': 'If you bought everything from one store instead:',
    'store_missing_items_singular': '{store} ({count} item unavailable)',
    'store_missing_items_plural': '{store} ({count} items unavailable)',
    'total_cost': 'Total Cost',
    'enter_valid_budget_amount': 'Enter a valid budget amount',
    'budget_saved': 'Budget saved',
    'could_not_save_budget': 'Could not save your budget',
    'could_not_load_budget': 'Could not load your budget.',
    'set_budget': 'Set Budget',
    'save_budget': 'Save Budget',
    'budget_used': 'Budget Used',
    'exceeded_budget_message': 'You have exceeded your budget.',
    'cheaper_alternatives': 'Cheaper Alternatives',
    'try_alternative': 'Try {name}',
    'save_amount': 'Save RM{amount}',
    'password_reset_sent': 'Password reset email sent. Please check your inbox and spam folder.',
    'password_reset_sent_generic': 'If an account exists for this email, a password reset email has been sent.',
    'forgot_password_title': 'Forgot Password?',
    'forgot_password_subtitle': "Enter the email address associated with your account and we'll send you a password reset link.",
    'email_address': 'Email Address',
    'please_enter_email': 'Please enter your email',
    'please_enter_valid_email': 'Please enter a valid email address',
    'send_reset_link': 'Send Reset Link',
    'remember_password_question': 'Remember your password? ',
    'smart_grocery': 'Smart Grocery',
    'shopping_assistant': 'Shopping Assistant',
    'register': 'Register',
    'continue_as_guest': 'Continue as Guest',
    'google_sign_in_failed': 'Google sign in failed.',
    'incorrect_email_or_password': 'Incorrect email or password.',
    'account_disabled': 'This account has been disabled.',
    'too_many_login_attempts': 'Too many login attempts. Please try again later.',
    'login_failed_try_again': 'Login failed. Please try again.',
    'something_went_wrong': 'Something went wrong.',
    'welcome_back': 'Welcome Back!',
    'login_subtitle': 'Login to continue to your account',
    'email': 'Email',
    'enter_your_email': 'Enter your email',
    'password': 'Password',
    'enter_your_password': 'Enter your password',
    'forgot_password_question': 'Forgot password?',
    'or': 'or',
    'continue_with_google': 'Continue with Google',
    'dont_have_account_question': "Don't have an account? ",
    'privacy_policy': 'Privacy Policy',
    'create_your_account': 'Create Your Account',
    'sign_up_subtitle': 'Sign up to get started with Smart Grocery',
    'full_name': 'Full Name',
    'please_enter_name': 'Please enter your name',
    'please_enter_password': 'Please enter a password',
    'password_length_error': 'Password must be at least 8 characters',
    'password_uppercase_error': 'Password must contain an uppercase letter',
    'password_lowercase_error': 'Password must contain a lowercase letter',
    'password_number_error': 'Password must contain a number',
    'confirm_password': 'Confirm Password',
    'passwords_do_not_match': 'Passwords do not match',
    'i_agree_to': 'I agree to the ',
    'terms_of_service': 'Terms of Service',
    'and': ' and ',
    'accept_terms_warning': 'Please accept the Terms of Service.',
    'account_created_verify': 'Account created! Please verify your email.',
    'registration_failed': 'Registration failed.',
    'sign_up_with_google': 'Sign up with Google',
    'already_have_account_question': 'Already have an account? ',
    'welcome_to': 'Welcome to',
    'email_not_verified_warning': 'Your email is still not verified. Please check your inbox and spam folder.',
    'verification_email_sent': 'Verification email sent.',
    'verify_your_email': 'Verify your email',
    'verify_email_subtitle': "We've sent a verification email to your inbox.\n\nOnce you've verified your email, press the button below.",
    'ive_verified_my_email': "I've Verified My Email",
    'resend_verification_email': 'Resend Verification Email',
    'cancel_registration_title': 'Cancel Registration?',
    'cancel_registration_message': "You'll be signed out and returned to the introduction screen. You can register again later with a different email address if needed.",
    'stay': 'Stay',
    'leave': 'Leave',
    'cancel_registration': 'Cancel Registration',
  };
}