class MalayStrings {
  static const Map<String, String> strings = {
    'settings': 'Tetapan',
    'preferences': 'KEUTAMAAN',
    'language': 'Bahasa',
    'notifications': 'Pemberitahuan',
    'mark_all': 'Tanda Semua',
    'clear_all': 'Padam Semua',
    'select_language': 'Pilih Bahasa',
    'no_notifications': 'Tiada pemberitahuan lagi — kegemaran produk untuk mendapatkan amaran harga.',
    'clear_notifications_title': 'Padam Semua Pemberitahuan',
    'clear_notifications_message': 'Ini akan memadam semua pemberitahuan. Tindakan ini tidak boleh dibatalkan.',
    'cancel': 'Batal',
    'confirm': 'Sahkan',
    'app_name': 'Smart Grocery',
    'coming_soon': 'Akan datang',
    'search_products': 'Cari produk...',
    'quick_actions': 'Tindakan Pantas',
    'search': 'Cari',
    'nearby': 'Berdekatan',
    'cart': 'Troli',
    'trends': 'Trend',
    'price_alerts': 'Amaran Harga',
    'view_all': 'Lihat Semua',
    'no_price_alerts': 'Tiada amaran harga lagi.',
    'recent_products': 'Produk Terkini',
    'no_recent_products': 'Tiada produk terkini lagi.',
    'guest': 'Tetamu',
    'registered_user': 'Pengguna Berdaftar',
    'dashboard': 'Papan Pemuka',
    'search_products_menu': 'Cari Produk',
    'nearby_supermarkets': 'Pasar Raya Berdekatan',
    'price_trends': 'Trend Harga',
    'my_budget': 'Belanjawan Saya',
    'favourites': 'Kegemaran',
    'profile': 'Profil',
    'about': 'Perihal',
    'logout': 'Log Keluar',
    'clear_recent_searches_title': 'Padam Carian Terkini',
    'clear_recent_searches_message': 'Ini akan memadam semua carian terkini anda.',
    'search_error': 'Sesuatu telah berlaku semasa membuat carian.',
    'removed_from_favourites': 'Dibuang daripada kegemaran',
    'added_to_favourites': 'Ditambah ke kegemaran',
    'added_to_cart': 'Ditambah ke troli',
    'please_try_again': 'Sila cuba lagi',
    'view': 'Lihat',
    'search_products_hint': 'Cari produk (cth. ayam, beras, minyak)...',
    'filter': 'Penapis',
    'results': 'Keputusan',
    'no_products_found': 'Tiada produk dijumpai — cuba carian lain.',
    'clear_filters': 'Kosongkan Penapis',
    'or_browse_category': 'Atau semak imbas mengikut kategori',
    'search_prompt': 'Cari produk untuk membandingkan harga di antara pasar raya.',
    'product_details': 'Butiran Produk',
    'product_not_found': 'Produk ini tidak dijumpai.',
    'could_not_load_product': 'Gagal memuatkan produk ini.',
    'add_to_cart': 'Tambah ke Troli',
    'could_not_load_pricing': 'Gagal memuatkan harga untuk produk ini.',
    'no_price_data': 'Tiada data harga untuk produk ini lagi.',
    'price_varies_by_store': 'Harga mungkin berbeza mengikut kedai',
    'cheapest_at': 'Termurah di',
    'avg_price': 'Harga Purata',
    'price_trend': 'Trend Harga',
    'trend_rising': 'Meningkat',
    'trend_falling': 'Menurun',
    'trend_stable': 'Stabil',
    'price_comparison': 'Perbandingan Harga',
    'view_all_stores': 'Lihat Semua Kedai',
    'product_information': 'Maklumat Produk',
    'category': 'Kategori',
    'item_group': 'Kumpulan Barangan',
    'unit': 'Unit',
    'compare_prices': 'Bandingkan Harga',
    'could_not_load_prices': 'Gagal memuatkan harga untuk produk ini.',
    'could_not_load_supermarkets': 'Gagal memuatkan butiran pasar raya.',
    'sort': 'Isih:',
    'sort_price': 'Harga',
    'sort_distance': 'Jarak',
    'sort_alphabetical': 'Abjad',
    'tap_store_to_add': 'Ketik kedai untuk menambah',
    'lowest': 'Terendah',
    'average': 'Purata',
    'highest': 'Tertinggi',
    'cheapest': 'Termurah',
    'locating': 'Mencari lokasi…',
    'all_categories': 'Semua Kategori',
    'price_range': 'Julat Harga',
    'sort_by': 'Isih Mengikut',
    'reset': 'Set Semula',
    'apply': 'Guna',
    'recent_searches': 'Carian Terakhir',
    'no_price_history_available': 'Tiada sejarah harga tersedia.',
    'date': 'Tarikh',
    'store': 'Kedai',
    'price': 'Harga',
    'supermarket': 'Pasar Raya',
    'search_results': 'Keputusan Carian',
    'could_not_load_products': 'Gagal memuatkan produk.',
    'search_product_hint': 'Cari produk...',
    'search_trend_instruction': 'Taip di ruang carian untuk mencari trend harga produk.',
    'no_notifications_yet': 'Tiada pemberitahuan lagi — kegemaran produk untuk mendapatkan amaran harga.',
    'clear_all_notifications_title': 'Padam Semua Pemberitahuan',
    'clear_all_notifications_message': 'Ini akan memadam semua pemberitahuan. Tindakan ini tidak boleh dibatalkan.',
    'could_not_load_notifications': 'Gagal memuatkan pemberitahuan.',
    'just_now': 'Baru sahaja',
    'min_ago': 'min lepas',
    'hours_ago': 'jam lepas',
    'days_ago': 'hari lepas',
    'price_unavailable': 'Harga tidak tersedia',
    'view_details': 'Lihat Butiran',
    'remove': 'Padam',
    'clear_all_favourites_title': 'Padam Semua Kegemaran',
    'clear_all_favourites_message': 'Ini akan memadam semua produk kegemaran. Tindakan ini tidak boleh dibatalkan.',
    'log_in_to_save_favourites': 'Log masuk untuk simpan kegemaran',
    'log_in_to_save_favourites_desc': 'Simpan produk kegemaran anda dan dapatkan pemberitahuan apabila harga berubah.',
    'login': 'Log Masuk',
    'your_favourites': 'Kegemaran Anda',
    'your_favourites_desc': 'Akses pantas ke produk yang anda simpan untuk kemudian.',
    'search_favourites_hint': 'Cari kegemaran...',
    'all_favourites': 'Semua Kegemaran',
    'done': 'Selesai',
    'edit': 'Sunting',
    'no_favourites_added': 'Anda belum menambah sebarang kegemaran lagi.',
    'no_favourites_matched': 'Tiada kegemaran yang sepadan dengan carian anda.',
    'could_not_load_favourites': 'Gagal memuatkan kegemaran anda.',
    'filter_supermarkets': 'Tapis Pasar Raya',
    'open_now': 'Buka Sekarang',
    'minimum_rating': 'Penarafan Minimum',
    'and_above': '& Ke Atas',
    'maximum_distance': 'Jarak Maksimum',
    'location_required': 'Lokasi Diperlukan',
    'location_service_disabled_msg': 'Sila hidupkan perkhidmatan lokasi peranti anda untuk mencari pasar raya berdekatan.',
    'location_permission_denied_msg': 'Sila benarkan kebenaran lokasi untuk mencari pasar raya berdekatan.',
    'turn_on_location': 'Hidupkan Lokasi',
    'grant_permission': 'Berikan Kebenaran',
    'retry': 'Cuba Lagi',
    'no_internet_title': 'Tiada Sambungan Internet',
    'no_internet_message': 'Anda sedang luar talian. Sila semak sambungan anda dan cuba lagi.',
    'all': 'Semua',
    'grocery': 'Barangan Runcit',
    'hypermarket': 'Pasar Raya Besar',
    'convenience': 'Kedai Serbaneka',
    'search_supermarket_hint': 'Cari pasar raya...',
    'open': 'Buka',
    'closed': 'Tutup',
    'navigate': 'Navigasi',
    'view_prices': 'Lihat Harga',
    'nearby_stores': 'Kedai Berdekatan',
    'found': 'dijumpai',
    'no_supermarkets_found': 'Tiada pasar raya dijumpai.',
    'address': 'Alamat',
    'product_catalogue': 'Katalog Produk',
    'no_product_data_title': 'Tiada data produk lagi',
    'no_product_data_desc': 'Produk yang terdapat di pasar raya ini akan dipaparkan di sini.',
    'check_connection_retry': 'Sila semak sambungan anda dan cuba lagi.',
    'no_comparison_data_title': 'Tiada data perbandingan lagi',
    'no_comparison_data_desc': 'Bandingkan harga produk dengan pasar raya lain.',
    'could_not_load_comparison': 'Gagal memuatkan perbandingan',
    'no_products_found_desc': 'Kami belum mempunyai data harga untuk produk kedai ini lagi.',
    'approximate_match_warning': 'Menunjukkan kedai padanan terdekat dalam pangkalan data harga kami — ia mungkin bukan padanan tepat.',
    'showing_products_count': 'Menunjukkan {shown} daripada {total} produk yang terdapat di kedai ini.',
    'best_prices_found_title': 'Harga terbaik dijumpai di sini',
    'best_prices_found_desc': 'Kedai ini sudah mempunyai harga terendah yang kami temui untuk produknya.',
    'price_here_vs_elsewhere': 'RM{here} di sini · RM{elsewhere} di tempat lain',
    'price_each': 'RM{price} setiap satu',
    'choose_a_store': 'Choose a Store',
    'could_not_load_store_options': 'Could not load store options for this product.',
    'no_store_price_available': 'No store currently has a price for this product.',
    'clear_cart': 'Kosongkan Troli',
    'clear_cart_message': 'Ini akan memadam semua barangan daripada troli anda.',
    'removed_item': '{name} dipadamkan',
    'undo': 'Batal',
    'empty_cart_message': 'Troli anda kosong.\nTambah produk semasa menyemak imbas atau membandingkan harga.',
    'could_not_load_cart': 'Gagal memuatkan troli anda.',
    'cheapest_single_store': 'Kedai Tunggal Termurah',
    'single_store_comparison_subtitle': 'Jika anda membeli segalanya dari satu kedai sahaja:',
    'store_missing_items_singular': '{store} ({count} barang tidak tersedia)',
    'store_missing_items_plural': '{store} ({count} barang tidak tersedia)',
    'mixed_store_total': 'Jumlah Gabungan Kedai',
    'mixed_store_total_subtitle': 'Beli setiap barang dari kedai termurahnya, merentasi {count} kedai:',
    'mixed_store_savings': 'Jimat RM{amount} berbanding satu kedai',
    'total_cost': 'Jumlah Kos',
    'complete_shopping': 'Selesaikan Belian',
    'complete_shopping_message': 'Ini akan menamatkan sesi belian anda dan mengosongkan troli anda. Tindakan ini tidak boleh dibatalkan.',
    'shopping_completed': 'Belian selesai! Troli anda telah dikosongkan.',
    'enter_valid_budget_amount': 'Masukkan jumlah bajet yang sah',
    'budget_saved': 'Bajet disimpan',
    'could_not_save_budget': 'Gagal menyimpan bajet anda',
    'could_not_load_budget': 'Gagal memuatkan bajet anda.',
    'set_budget': 'Tetapkan Bajet',
    'save_budget': 'Simpan Bajet',
    'budget_used': 'Bajet Digunakan',
    'exceeded_budget_message': 'Anda telah melebihi bajet anda.',
    'cheaper_alternatives': 'Alternatif Lebih Murah',
    'try_alternative': 'Cuba {name}',
    'save_amount': 'Jimat RM{amount}',
    'password_reset_sent': 'E-mel penyetelan semula kata laluan telah dihantar. Sila semak peti masuk dan folder spem anda.',
    'password_reset_sent_generic': 'Jika akaun wujud untuk e-mel ini, e-mel penyetelan semula kata laluan telah dihantar.',
    'forgot_password_title': 'Lupa Kata Laluan?',
    'forgot_password_subtitle': 'Masukkan alamat e-mel yang dikaitkan dengan akaun anda dan kami akan menghantar pautan penyetelan semula kata laluan.',
    'email_address': 'Alamat E-mel',
    'please_enter_email': 'Sila masukkan e-mel anda',
    'please_enter_valid_email': 'Sila masukkan alamat e-mel yang sah',
    'send_reset_link': 'Hantar Pautan Penyetelan',
    'remember_password_question': 'Ingat kata laluan anda? ',
    'smart_grocery': 'Barangan Runcit Pintar',
    'shopping_assistant': 'Pembantu Membeli-Belah',
    'register': 'Daftar',
    'continue_as_guest': 'Teruskan sebagai Tetamu',
    'google_sign_in_failed': 'Log masuk Google gagal.',
    'incorrect_email_or_password': 'E-mel atau kata laluan tidak betul.',
    'account_disabled': 'Akaun ini telah dinyahdayakan.',
    'too_many_login_attempts': 'Terlalu banyak percubaan log masuk. Sila cuba lagi kemudian.',
    'login_failed_try_again': 'Log masuk gagal. Sila cuba lagi.',
    'something_went_wrong': 'Sesuatu yang tidak kena telah berlaku.',
    'welcome_back': 'Selamat Kembali!',
    'login_subtitle': 'Log masuk untuk meneruskan ke akaun anda',
    'email': 'E-mel',
    'enter_your_email': 'Masukkan e-mel anda',
    'password': 'Kata Laluan',
    'enter_your_password': 'Masukkan kata laluan anda',
    'forgot_password_question': 'Lupa kata laluan?',
    'or': 'atau',
    'continue_with_google': 'Teruskan dengan Google',
    'dont_have_account_question': 'Belum mempunyai akaun? ',
    'privacy_policy': 'Dasar Privasi',
    'create_your_account': 'Cipta Akaun Anda',
    'sign_up_subtitle': 'Daftar untuk bermula dengan Barangan Runcit Pintar',
    'full_name': 'Nama Penuh',
    'please_enter_name': 'Sila masukkan nama anda',
    'please_enter_password': 'Sila masukkan kata laluan',
    'password_length_error': 'Kata laluan mestilah sekurang-kurangnya 8 aksara',
    'password_uppercase_error': 'Kata laluan mesti mengandungi huruf besar',
    'password_lowercase_error': 'Kata laluan mesti mengandungi huruf kecil',
    'password_number_error': 'Kata laluan mesti mengandungi nombor',
    'confirm_password': 'Sahkan Kata Laluan',
    'passwords_do_not_match': 'Kata laluan tidak sepadan',
    'i_agree_to': 'Saya bersetuju dengan ',
    'terms_of_service': 'Syarat Perkhidmatan',
    'and': ' dan ',
    'accept_terms_warning': 'Sila terima Syarat Perkhidmatan.',
    'account_created_verify': 'Akaun dicipta! Sila sahkan e-mel anda.',
    'registration_failed': 'Pendaftaran gagal.',
    'sign_up_with_google': 'Daftar dengan Google',
    'already_have_account_question': 'Sudah mempunyai akaun? ',
    'welcome_to': 'Selamat datang ke',
    'email_not_verified_warning': 'E-mel anda masih belum disahkan. Sila semak peti masuk dan folder spem anda.',
    'verification_email_sent': 'E-mel pengesahan telah dihantar.',
    'verify_your_email': 'Sahkan e-mel anda',
    'verify_email_subtitle': 'Kami telah menghantar e-mel pengesahan ke peti masuk anda.\n\nSebaik sahaja anda mengesahkan e-mel anda, tekan butang di bawah.',
    'ive_verified_my_email': 'Saya Telah Mengesahkan E-mel Saya',
    'resend_verification_email': 'Hantar Semula E-mel Pengesahan',
    'cancel_registration_title': 'Batalkan Pendaftaran?',
    'cancel_registration_message': 'Anda akan dilog keluar dan dikembalikan ke skrin pengenalan. Anda boleh mendaftar semula kemudian dengan alamat e-mel yang berbeza jika perlu.',
    'stay': 'Kekal',
    'leave': 'Keluar',
    'cancel_registration': 'Batalkan Pendaftaran',
    'guest_profile_title': 'Cipta akaun',
    'guest_profile_desc': 'Simpan profil, kegemaran, dan amaran harga anda dengan mencipta akaun.',
    'email_status': 'Status E-mel',
    'email_verified': 'Disahkan',
    'email_not_verified': 'Belum Disahkan',
    'member_since': 'Ahli Sejak',
    'logout_confirm_title': 'Log Keluar?',
    'logout_confirm_message': 'Anda perlu log masuk semula untuk mengakses akaun anda.',
    'take_photo': 'Ambil Gambar',
    'choose_from_gallery': 'Pilih daripada Galeri',
    'remove_photo': 'Padam Gambar',
    'edit_photo': 'Sunting Gambar',
    'photo_updated': 'Gambar profil dikemas kini',
    'photo_removed': 'Gambar profil dipadamkan',
    'could_not_update_photo': 'Gagal mengemas kini gambar profil anda.',
    'app_version': 'Versi',
    'legal': 'UNDANG-UNDANG',
  };
}